idf_component_register(
    SRCS
        "app_main.c"
        "lwm2m/lwm2m_client_handler.c"
        "lwm2m/lwm2m_sensor.c"
        "maintenance/button_hold.c"
        "maintenance/maintenance_button.c"
        "network/time_sync.c"
        "network/wifi_provisioning.c"
        "sensors/dht11.c"
        "sensors/dht11_decode.c"
        "storage/cert_manager.c"
        "storage/spiffs_utils.c"
    INCLUDE_DIRS
        "."
    PRIV_REQUIRES
        anjay
        esp_driver_gpio
        esp_driver_rmt
        esp_event
        esp_netif
        lwip
        esp_rom
        esp_timer
        esp_wifi
        nvs_flash
        spiffs
)
